# -*- coding: utf-8 -*-
"""(03-17) 이민성 오후 과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1oMMukXQ1qLPcaoPiRElMukopnBXISt
"""



"""# > 제곱 문제
사용자에게 입력받은 수의 제곱을 계산하여 출력하는 코드를 작성하시오

*   a=3, 결과 -> 9 출력
*   b=5, 결과 -> 25 출력


"""

a = int(input("a의 숫자를 입력하세요: "))
print("a의 제곱은 %d 입니다" %(a ** 2))

b = int(input("b의 숫자를 입력하세요: "))
print("b의 제곱은 %d 입니다" %(b ** 2))

"""# > 문자열 인덱싱 문제
문자열 인덱싱 또는 슬라이싱을 사용하여 년 월일 날씨를 출력하시오.

*   text = '20230601sunnyy'
*   year = '2023'
*   day = '01'
*   weather = 'sunny'
"""

text = '20230601sunny'
year = text[:4]
day = text[4:8]
weather = text[8:]

print("text = %s"% text)
print("year = %s"% year)
print("day = %s"% day)
print("weather = %s"% weather)

"""# > 전화번호 형식 바꾸기 문제
010-1234-5678의 형식으로 저장된 전화번호를 '-'을 제거해 01012345678의 형식으로 바꿔보시오.

*   문자열 내장 함수를 사용하면 해결할 수 있습니다.
*   문자열 슬라이싱을 이용해도 상관없습니다.


"""

num = '010-1234-5678'

result = num.replace("-","")
print(result)

"""# > 제목글 변환 문제
사용자에게 영어로된 문자열을 입력받고, 첫 문자만 대문자로 변경하시오.
입력 : i am a boy
출력 : I am a boy
"""

str = input("문자열 입력 : ")
print("변경된 문자열 : %s" % str.capitalize())

"""# > 문자열 분할 문제(split)

카카오톡의 대화 정보는 다음과 같이 저장된다.
"2023년 1월 2일 오후 9:52, 유연휘 : 일단"
위 문장을, 날짜, 시간, 이름, 내용별로 분할해보자.

"""

kakaotalk = "2023년 1월 2일 오후 9:52, 유연휘 : 일단"

kakaotalk = kakaotalk.replace(",","")
kt = kakaotalk.split()

print("년 = %s" % kt[0])
print("월 = %s" % kt[1])
print("일 = %s" % kt[2])
print("시간 = %s" % kt[3:5])
print("이름 = %s" % kt[5])
print("내용 = %s" % kt[7])